# Generated by Django 4.2.3 on 2023-09-13 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_no", models.CharField(max_length=255, unique=True)),
                ("stage_of_case", models.CharField(max_length=100)),
                ("respondent_name", models.CharField(max_length=255)),
                ("respondent_advocate", models.CharField(max_length=255)),
                (
                    "client_role",
                    models.CharField(
                        choices=[
                            ("Petitioner", "Petitioner"),
                            ("Respondent", "Respondent"),
                        ],
                        max_length=255,
                    ),
                ),
                ("case_description", models.TextField(blank=True, null=True)),
                ("sense_of_urgent", models.CharField(max_length=20)),
                ("court_no", models.CharField(max_length=40)),
                ("judge_name", models.CharField(blank=True, max_length=100, null=True)),
                ("court_remark", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case_type", models.CharField(max_length=100)),
                ("case_description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="CourtType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("court_type", models.CharField(max_length=100)),
                ("court_description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date_time", models.DateTimeField(auto_now_add=True)),
                ("final_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid", models.BooleanField(default=False)),
                ("short_descriptions", models.TextField(max_length=100, null=True)),
                (
                    "total_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=1000),
                ),
                (
                    "total_prof_service_price",
                    models.DecimalField(decimal_places=2, max_digits=1000),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="myadmin.case"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.CreateModel(
            name="ReimburService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=1000)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "ReimburService",
                "verbose_name_plural": "ReimburService",
            },
        ),
        migrations.CreateModel(
            name="ProfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prof_service", models.CharField(max_length=100)),
                (
                    "prof_service_price",
                    models.DecimalField(decimal_places=2, max_digits=1000),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProfService",
                "verbose_name_plural": "ProfService",
            },
        ),
        migrations.CreateModel(
            name="ClientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=100)),
                ("identity", models.CharField(max_length=50, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("address1", models.CharField(max_length=200)),
                ("address2", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("remark", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "agent_fullname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("agent_ph", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "agent_identity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="case_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myadmin.casetype"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="clients",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myadmin.clientrecord"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="court_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myadmin.courttype"
            ),
        ),
    ]
