# Generated by Django 4.2.5 on 2023-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reimburservice",
            name="service",
        ),
        migrations.RemoveField(
            model_name="reimburservice",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="reimburservice",
            name="reimbur_service",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reimburservice",
            name="reimbur_service_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=1000, null=True
            ),
        ),
    ]
