# Generated by Django 4.2.3 on 2023-09-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="client_role",
            field=models.CharField(
                choices=[("Petitioner", "Petitioner"), ("Respondent", "Respondent")],
                max_length=255,
            ),
        ),
    ]
