# Generated by Django 4.2.3 on 2023-09-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case_type", models.CharField(max_length=100)),
                ("case_description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="CourtType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("court_type", models.CharField(max_length=100)),
                ("court_description", models.CharField(max_length=500)),
            ],
        ),
    ]
