# Generated by Django 4.2.5 on 2023-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientrole",
            name="client_role_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="courttype",
            name="court_description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
