# Generated by Django 4.2.5 on 2023-10-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0002_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=1000, null=True
            ),
        ),
    ]
