# Generated by Django 4.2.5 on 2023-10-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0003_transaction_transaction_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="final_total_transaction",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
