# Generated by Django 4.2.5 on 2023-10-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0003_rename_total_unit_price_invoice_total_reimbur_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myadmin.case",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date_time",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
