# Generated by Django 4.2.5 on 2023-09-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0003_alter_case_court_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="court_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myadmin.courttype",
            ),
        ),
    ]
