# Generated by Django 4.2.3 on 2023-09-03 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0003_casetype_created_by_courttype_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casetype",
            name="created_by",
        ),
    ]
