# Generated by Django 4.2.5 on 2023-10-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0004_alter_invoice_case_alter_invoice_invoice_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="case",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myadmin.case",
            ),
        ),
    ]
