# Generated by Django 4.2.3 on 2023-09-03 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0004_remove_casetype_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courttype",
            name="created_by",
        ),
    ]
