# Generated by Django 4.2.3 on 2023-09-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0006_case_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="id",
        ),
        migrations.AddField(
            model_name="case",
            name="case_id",
            field=models.CharField(
                default="CASE-00001", max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
