# Generated by Django 4.2.3 on 2023-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0007_remove_case_id_case_case_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="role",
            new_name="client_role",
        ),
        migrations.RemoveField(
            model_name="case",
            name="case_id",
        ),
        migrations.AddField(
            model_name="case",
            name="description",
            field=models.TextField(default="SOME STRING"),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_name",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
