# Generated by Django 4.2.3 on 2023-09-06 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myadmin", "0008_rename_role_client_client_role_remove_case_case_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=100)),
                ("identity", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("address1", models.CharField(max_length=200)),
                ("address2", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("remark", models.CharField(max_length=500)),
                ("agent_fullname", models.CharField(max_length=100)),
                ("agent_ph", models.CharField(max_length=50)),
                ("agent_identity", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cusrecord",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Record",
        ),
        migrations.DeleteModel(
            name="cusRecord",
        ),
    ]
