# Generated by Django 4.2.3 on 2023-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0009_clientrecord_remove_cusrecord_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientrecord",
            name="agent_fullname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientrecord",
            name="agent_identity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="clientrecord",
            name="agent_ph",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="clientrecord",
            name="remark",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
